### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by jimisaacs** [mikeal/replicate#2]
There's a couple issues I noticed.
The required node version doesn't exist as a tag anymore.
It requires two dependencies not listed in the package.json, but exist in this repo.
The sys module is used when it has been renamed to util, and this module isn't even used anyway.
It throws an error when usage is wrong, is this necessary? My first thought was something else was wrong with my platform.

Basically, this module is interesting to me, and most likely others, because there's a few threads that end up pointing to here because there's no many bugs with the built-in couch db replicator.

Thank you, This thing was a life saver when setting up an npm registry clone.

I'm not quite sure how it works yet, because when I run it and it exits the process saying "replication complete", sometimes I still see that it leaves the couch processes of main.js running, and I'm wondering if this is a bug.

**Comment by mikeal** [comment]
its still maintained, I've just been a little lazy about updating the deps, I'll get to it this week.

**Comment by mmalecki** [comment]
@mikeal I've fixed dependencies and removed `sys` usage in my [`fixes` branch](https://github.com/mmalecki/replicate/tree/fixes). It should be installable from npm now. Diff is [here](https://github.com/mmalecki/replicate/compare/master...fixes). Feel free to merge it.

**Comment by jimisaacs** [comment]
Thanks guys!

**Comment by mikeal** [comment]
can we convert this in to a pull request to make the code review easier?

**Comment by mikeal** [comment]
i wrote all this code in the last few months, why the hell was I requiring sys! i should have my head examined. thanks btw :)

**Comment by mmalecki** [comment]
@mikeal Sure, there you go: #3 :).

**Comment by mikeal** [comment]
merged.
