### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by japj** [mikeal/replicate#8]
Hi,

I'm trying to replicate the npm couchdb and replicate memory usage slowly increases until it hits about 1.8Gb and then the nodejs process exits.

This is with node 0.6.17

**Comment by kmpm** [comment]
I can confirm. Got the same issue.
Ubuntu 12.04 default node version 0.6.12 and couchdb version 1.0.1

replicate installed from npm and is version 0.2.0.

It uses up RAM quickly and I don't know why

**Comment by thinkadoo** [comment]
I have the same on OS X 10.9.5 npm 2.1.3
